In [1]:
import pandas as pd, json

pd.read_csv("data/circulation_data.csv").head()

,transaction_id,member_id,isbn,checkout_date,return_date,branch_id
0,TXN000000,M93810,978-0-551-16436-9,2026-06-01,2026-06-25,BR004
1,TXN000001,M23434,978-0-9725401-4-8,2024-12-20,2024-12-22,BR002
2,TXN000002,M13905,978-1-203-70878-8,2026-04-24,2026-05-12,BR009
3,TXN000003,M36062,978-1-07-024748-9,2025-07-21,2025-08-09,BR007
4,TXN000004,M46463,978-1-71434-558-8,2026-04-08,2026-05-01,BR013

In [2]:
with open("data/events_data.json") as f:
    data = json.load(f)
print(type(data), len(data))

<class 'list'> 500

In [3]:
pd.read_excel("data/catalogue.xlsx", sheet_name=0).head()

,ISBN,Title,Author,Genre,Publication Year,Copies Available,Acquisition Date,Status
0,978-0-433-21819-7,Universal value-added matrix,Allan Roberts,Children,1998,4,2024-04-30,Damaged
1,978-0-01-338908-8,Monitored global pricing structure,Grace Davison,Young Adult,1962,1,2020-03-12,Reserved
2,978-1-379-40265-7,Cross-group multi-state capacity,Dr Kirsty Johnson,Reference,2021,2,2019-11-15,Available
3,9780351161551,Networked didactic policy,Carole Thompson,Reference,2009,0,2017-06-14,Missing
4,978-0-7816-1849-6,Managed eco-centric monitoring,Lewis Ali-Wilkinson,Reference,1985,1,2025-03-07,Available